# Generated by Django 5.1.4 on 2025-04-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
